import Head from "next/head";
import { Roboto } from "next/font/google";
import styles from "@/styles/Home.module.css";

const RobotoSans = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export default function Home() {
  const [input, setInput] = useState('');
  const [result, setResult] = useState([]);

  const handleInputChange = (e) => {
    setInput(e.target.value);
  };

  const calculateFrequency = () => {
    const cleanedInput = input.replace(/[^a-zA-Z]/g, '').toLowerCase();
    const frequencyMap = {};

    for (let char of cleanedInput) {
      frequencyMap[char] = (frequencyMap[char] || 0) + 1;
    }

    const frequencyArray = Object.keys(frequencyMap).map((char) => ({
      char,
      frequency: ((frequencyMap[char] / cleanedInput.length) * 100).toFixed(2),
    }));

    frequencyArray.sort((a, b) => b.frequency - a.frequency);

    setResult(frequencyArray);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.page} ${RobotoSans.variable}`}>
        <div></div>
      </div>
    </>
  );
}
