import Head from "next/head";
import { Roboto } from "next/font/google";
import LetterFrequencyAnalyzer from "./component/frequencyAnalyser/frequencyAnalyser";

const RobotoSans = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Identificar letras mais frequentes</title>
        <meta name="description" content="Generated by Andresa A Ribeiro" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${RobotoSans.variable}`}>
        <LetterFrequencyAnalyzer />
      </div>
    </>
  );
}
